### ISSUE TITLE
Confirm tracking camera selection

### ISSUE THREAD

**Issue by dlllonb** [UChicago-PULSE/mission-documentation#35]
I know Juan wanted this done, and we've been nearly done with this for quite a while. Just making this issue so we get it officially resolved. 

As far as I know, the current choice is: [ASI294MM Pro](https://www.highpointscientific.com/zwo-asi294mm-pro-monochrome-cooled-camera-asi294mm-p?utm_source=google&utm_medium=cse&utm_term=ZWO-ASI294MM-P&utm_source=google&utm_medium=cpc&utm_campaign=20618277309&utm_content=&utm_term=&gad_source=1&gclid=CjwKCAjwz42xBhB9EiwA48pT7zO0Nh9wBSgfprDYf6N71UnqXAONDADp54Kd4aOgZbC3vRv3-lbDpxoC00MQAvD_BwE)

I want final opinions and confirmation though. Though I have a decent amount of experience with these cameras, most of them look fairly the same at this point. So if anyone wants specific stuff, speak now. 

People I think should sign off on this: @rohangupta2806 @jipa2004 @knightss27 @glask123 @MasonMcCormack, maybe I'm missing some people.

**Comment by dlllonb** [comment]
as of now, confirmed for ASI294MM Pro

**Comment by MasonMcCormack** [comment]
The camera looks good, I sent an email to a telescope manager to double-check if they had any thoughts or other ideas, but this works.
